### ISSUE TITLE
repository purpose - clean up the content

### ISSUE THREAD

**Issue by antje-s** [World-Meteorological-Organization/pywis-pubsub#2]
If we want to use this repository for python library, we should delete code that I had initially put in for docker container that includes sub and download function. A mix is not good from my point of view

**Comment by maaikelimper** [comment]
I agree we should delete the code in the mqp-subscriber if all functions are integrated in the main package

**Comment by maaikelimper** [comment]
apart from 'mqp-subscriber'-folder which I understand is the original code we now have:
- pywis_downloader and pywis_subscriber 
- pywis_pubsub 
I would be good if we could integrate the different pieces of code rather than adding more separate folders.

**Comment by antje-s** [comment]
Code was not integrated in the main package but it should not be mixed in one repository so I deleted docker solution files
