### ISSUE TITLE
data_id used as filename ?

### ISSUE THREAD

**Issue by maaikelimper** [World-Meteorological-Organization/pywis-pubsub#27]
I noted that pywis-pubsub uses data_id as filename
```
        filename = msg_dict['properties']['data_id']

        storage_class = STORAGES[userdata.get('storage').get('type')]
        storage_object = storage_class(userdata['storage'])
        storage_object.save(data, filename)
```

Should we not take the filename of the canonical-href if the data is downloaded from a URL ? We risk looking the file-extension by saving data in this way. 

Or is this done on purpose so that when the same data_id arrives from 2 caches, data is effectively deduplicated as the data from a later cache would overwrite the data from the earlier cache ?

**Comment by tomkralidis** [comment]
Yes, the `data_id` is used for the filename to be able to identify / deduplicate accordingly.

**Comment by tomkralidis** [comment]
Bringing [this discussion](https://github.com/wmo-im/pywis-pubsub/pull/31#issuecomment-1689946229) into this issue.

As part of pywis-pubsub download functionality, current behaviour is as follows:
- user provides a basepath to prepend to all data downloads
- pywis-pubsub has the notification message's `properties.data_id` to uniquely identify the data, which contains topic information per the specification

PR #31 allows for a configurable storage path to use either `properties.data_id` (default) or `$.links[?(@.rel==="canonical")].href` to save the given data to a filepath

Given `properties_id.data_id` contains the topic, @mgiannoni would like the downloaded file to have the associated file extension, which may or may not be part of a canonical link (imagine a URL from an API).

Suggested approach:
- add `storage.filepath` option with the following options:
  - `data_id`: uses `properties.data_id` verbatim(default)
  - `link`: uses canonical link verbatim
  - `combined`: uses `properties.data_id` and tries to derive file extension:
    1. check canonical link href for a file extension; if found, append to filename (so data_id + extension)
    2. if no file extension is found, check for the canonical link's `type` property and derive a file extension from the media type
    3. if both 1 and 2 cannot be achieved, give up and log, writing using only `properties.data_id`


Thoughts?

**Comment by mgiannoni** [comment]
Good approach.  Proper catch for cases where file name extension is missing and managing the edge case where the MIME type is not defined.

**Comment by tomkralidis** [comment]
Thanks @mgiannoni. PR #31 updated to reflect the above [strategy/approach](https://github.com/wmo-im/pywis-pubsub/issues/27#issuecomment-1690265225).
