### ISSUE TITLE
separation of the subscription and the download function wanted?

### ISSUE THREAD

**Issue by antje-s** [World-Meteorological-Organization/pywis-pubsub#3]
Is a separation of the subscription and the download function wanted? If no separation - we can simply use Tom's solution and delete other code

**Comment by maaikelimper** [comment]
Tom's solution allows a user to subscribe and to optionally add the argument --download
```
# connect, and simply echo messages
pywis-pubsub subscribe --config local.yml

# connect, and download messages
pywis-pubsub subscribe --config local.yml --download
```

This solution looked OK for me.

**Comment by antje-s** [comment]
Yes, download is done via on_message_handler --> get_data. 
So the download is executed directly when a message is received. This could lead to problems with large downloads. In docker it was passed to Aria2 service and the download was taken over by the service so that the sub program can go directly to the next message again. In the split solution this is implemented via a shared directory. 
Possibly such problems do not occur when using in the wis2box, I have no problem to take first the solution of Tom and wait and see if it comes to problems. We can always change. Therefore I have now deleted the two folders for the separate scripts and the docker solution parts
