### ISSUE TITLE
Message validation error when attempting to download data from the France global broker

### ISSUE THREAD

**Issue by RoryPTB** [World-Meteorological-Organization/pywis-pubsub#42]
When I attempt to download data from globalbroker.meteo.fr, each message states `Data verification failed; not saving`, and no data is downloaded at all. Here is a sample of the output:
```
$ pywis-pubsub subscribe --config france-config.yml --download
Connected to broker mqtts://globalbroker.meteo.fr:8883
Subscribing to subscribe_topics ['origin/#', 'cache/#']
Data verification failed; not saving
Message is not a valid notification: <ValidationError: "{'data_id': 'wis2/bfa/ouagadougou_met_centre/data/core/weather/surface-based-observations/synop/WIGOS_0-20000-0-65503_20230807T210000', 'pubtime': '2023-08-07T21:36:02Z', 'integrity': {'method': 'sha512', 'value': 'e774891ef28366744926980fb16effc7e8a05611551bbeca93b0c3a254d60a7b93796c8efa16723248f90bad6f338c425669b6f6313d39a265ff1696e811e7dc'}, 'wigos_station_identifier': '0-20000-0-65503'} is not valid under any of the given schemas">
Message is not a valid notification: <ValidationError: '{} is not valid under any of the given schemas'>
Data verification failed; not saving
```
With the verbosity set to `INFO`, the URLs of the received messages are displayed and allow me to download the BUFR4 file.
With the verbosity set to `DEBUG`, [here](https://github.com/wmo-im/pywis-pubsub/files/12892122/example-validation-error-debug-no-dl.txt) is a sample of the output.

I can confirm this occurs when I am connected to the France global broker using MQTT Explorer. Here is the [config file](https://github.com/wmo-im/pywis-pubsub/files/12892092/france-config.txt) I used as a txt file (as GitHub does not support the yml extension).

**Comment by tomkralidis** [comment]
@RoryPTB can you try again? I'm unable to reproduce locally, and I believe we may have fixed a wis2box bug on message integrity in the interim, which would have fixed messages from WIS2 Nodes which are wis2box-powered.
