### ISSUE TITLE
add support for websockets

### ISSUE THREAD

**Issue by maaikelimper** [World-Meteorological-Organization/pywis-pubsub#44]
It is possible to subscribe to the Global Broker France using websockets:
`wss://globalbroker.meteo.fr:443/mqtt`

Could we add support for this in pywis-pubsub ? This would help users for whom port 8883 is blocked on their local network !:

**Comment by mgiannoni** [comment]
### Cases Where WebSocket $PATH Is Not "/mqtt"


<pre>
@@ -64,9 +70,15 @@ class MQTTPubSubClient:
         self.conn = mqtt_client.Client(self.client_id,
                                        userdata=self.userdata,
                                        transport=transport)
-
         self.conn.enable_logger(logger=LOGGER)

+        if self.broker_url.scheme in ['ws', 'wss']:
+            ws_headers = None     #The day will arrive when headers become important
+            LOGGER.debug('Setting Websockets parameters')
+            msg = f'Websocket path: {self.broker_url.path}'
+            LOGGER.debug(msg)
+            self.conn.ws_set_options(self.broker_url.path)
+
</pre>
