### ISSUE TITLE
fix typo in application/octet-stream

### ISSUE THREAD

**Issue by jmaxmarno** [World-Meteorological-Organization/pywis-pubsub#64]
should be "application/octet-stream"
https://github.com/wmo-im/pywis-pubsub/blob/9e650c140982b846c13ee8094bd9f0ea9924a922/pywis_pubsub/subscribe.py#L142C42-L142C65

**Comment by tomkralidis** [comment]
Thanks @jmaxmarno.  Fixed in d4b09f19a067960a2cd15aafe217bec06e2c5042
